### ISSUE TITLE
Feature title and Feature Body content

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Public-Policy#3]
We need a feature title and feature body content fro the home page.

**Comment by CVE82** [comment]
Moving this content to fill in those buckets..

<h1>Master of Public Policy</h1>

Temple University’s Master of Public Policy (MPP) program trains students and practitioners who seek successful careers in the public sector or in private or non-profit organizations that work on a continuous basis with government agencies.

**Comment by saracurnow** [comment]
Did this. I know we also need to add the SEO keywords, will put that on my list for tomorrow.
