### ISSUE TITLE
Question about header

### ISSUE THREAD

**Issue by saracurnow** [TULiberalArts/Public-Policy#4]
I just did the first round of editing MPP and Poli Sci with Joe and he told me to ask these questions. 

First: is there any way to change the header on the MPP page to say "Master of Public Policy" instead of "Public Policy" like it does now? I'm not talking about the feature header but the part right under "Temple University" and right above the tabs. Or do we need to alter the URL if we alter this? 

Thanks!

**Comment by CVE82** [comment]
No problem, thank you! Chris does not want the degree name in the title just the program name Public Policy, that you earn a Masters degree in. It is listed as Public Policy in the University bulletin as well and we are trying to stay consistent. http://bulletin.temple.edu/graduate/scd/cla/public-policy-mpp/

**Comment by saracurnow** [comment]
Understood! Thanks!
